web:
	./minesweeper.py --web

webDebug:
	# firefox http://localhost:5000
	./minesweeper.py --web --debug

terminal:
	./minesweeper.py --terminal

help:
	./minesweeper.py --help

runSafeDebug:
	FLASK_APP=minesweeper.py FLASK_ENV=development flask run

install:
	pip install flask --user
	pip install npyscreen --user
	pip install curses --user
